Add line/bar diagram reporting based on a card
pibizza/backstage-plugins pull request #16
Opened 2024-12-04 11:02 UTC by Rikkola

https://github.com/kiegroup/akrivis/issues/27

Expands the concept of the Card from just showing Score to also showing Reporting.

![image](https://github.com/user-attachments/assets/6ec4ae20-be09-421e-8a4f-37f47341c4c8)

2024-12-05 13:12 UTC, mareknovotny approved these changes

2024-12-20 09:49 UTC, Rikkola commented
Working on the conflicts.

2025-01-15 12:04 UTC, Rikkola commented
I changed the target to the currently active development branch.

2026-05-12 16:04 UTC, lucamolteni requested changes
can we close this?

2026-05-13 07:33 UTC, closed without merging